components:
  - ../../components/crossplane
  - ../../components/argocd
  - ../../components/traefik
  - ../../components/cert-manager
  - ../../components/sealed-secrets

bases:
- ../../base

resources:
  - secrets.sealed-secret.yaml
